name: Deploy Video Processor

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push video-processor
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/casgampro-video-processor:latest
            ${{ secrets.DOCKER_USERNAME }}/casgampro-video-processor:${{ github.sha }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no root@88.222.214.174 << EOF
            cd /root/casgampro
            docker compose pull video-processor
            docker compose up -d video-processor
          EOF
